// This file is generated by scripts/generate_neuron_params.py.
// Edit the Python source values and rerun the script instead of editing this file.
// Values, formats, and conversion method reproduce the research team's
// C_fixedpoint/Single_Neuron/neuron_fixed.c and
// C_fixedpoint/1D_Synfire/Synfire_1D_3neur_fixed.c reference models.
// DOI: 10.1109/JETCAS.2023.3330069

package neuron_params_generated_pkg;

    localparam int VALUE_WIDTH = 32;
    localparam int STATE_FRAC_BITS = 24;
    localparam int CONSTANT_FRAC_BITS = 24;
    localparam int MATRIX_FRAC_BITS = 23;
    localparam int CURRENT_FRAC_BITS = 8;
    localparam int TRIANGLE_FRAC_BITS = 16;

    typedef logic signed [VALUE_WIDTH-1:0] fixed_t;

    // Initial state order: Vmem, VK, Vg, VNa.
    localparam fixed_t INITIAL_STATE [0:3] = '{
        -32'sd47494620, 32'sd35804256, -32'sd74339848, -32'sd74339848
    };

    // Constants use 24 fractional bits unless stated otherwise.
    localparam fixed_t DT = 32'sd16777;
    localparam fixed_t EXPMEL = 32'sd122987056;
    localparam fixed_t EXPVSAT = 32'sd110924240;
    localparam fixed_t EXPMVGK = 32'sd3823527;
    localparam fixed_t EXPVNA = 32'sd305345;
    localparam fixed_t EXPEK = 32'sd2288412;
    localparam fixed_t KP = -32'sd12582912;

    // Input current uses 8 fractional bits.
    localparam fixed_t INPUT_PULSE_HEIGHT = 32'sd25600;

    // Matrix coefficients use 23 fractional bits.
    localparam fixed_t NEURON_MATRIX [0:3][0:7] = '{
        '{32'sd593788, 32'sd169595, 32'sd11150, 32'sd20030094, -32'sd200433440, -32'sd75717656, 32'sd1133899, -32'sd1947070},
        '{32'sd593788, 32'sd169595, 32'sd11150, 32'sd20030094, -32'sd200433440, -32'sd75717656, 32'sd3444937, -32'sd1947070},
        '{32'sd584353, 32'sd166900, 32'sd10973, 32'sd36721840, -32'sd367461312, -32'sd74514560, 32'sd1115882, 32'sd3569629},
        '{32'sd547831, 32'sd156469, 32'sd10287, 32'sd172703920, -32'sd1728181632, -32'sd69857400, 32'sd1046139, 32'sd198276688}
    };

    // Triangle states and slopes use Q16.16; Vmem threshold uses Q8.24.
    localparam fixed_t TRIANGLE_INITIAL_STATE_Q16 = 32'sd9454846;
    localparam fixed_t TRIANGLE_UPPER_BOUND_Q16 = 32'sd9454845;
    localparam fixed_t TRIANGLE_SPIKE_THRESHOLD_Q24 = 32'sd24397427;
    // Rows: excitatory, inhibitory. Columns: Vmem above, below threshold.
    localparam fixed_t TRIANGLE_SLOPE_MATRIX_Q16 [0:1][0:1] = '{
        '{-32'sd4668640, 32'sd882094},
        '{-32'sd17829738, 32'sd228674}
    };

    // Per-source synapse signals. Channel 0 is excitatory; 1 is inhibitory.
    localparam fixed_t SYNAPSE_TRIANGLE_SCALE_Q24 = 32'sd838860;
    localparam fixed_t SYNAPSE_GATE_OFFSET_Q16 [0:1] = '{32'sd8509364, 32'sd945487};
    localparam fixed_t SYNAPSE_EFFECTIVE_COUPLING_Q24 = -32'sd10066329;
    localparam fixed_t SYNAPSE_EXP_BIAS_Q24 [0:1] = '{32'sd1442840576, 32'sd318767104};
    localparam fixed_t SYNAPSE_EXCITATORY_SCALE_Q8 = 32'sd88;
    localparam fixed_t SYNAPSE_INHIBITORY_VMEM_OFFSET_Q24 = -32'sd130773365;

    // Fixed 3-neuron recurrent 1D synfire configuration.
    localparam int SYNFIRE_1D_3_NEURON_COUNT = 3;
    localparam int SYNFIRE_1D_3_STEPS = 190000;
    localparam int SYNFIRE_1D_3_PULSE_START = 60000;
    localparam int SYNFIRE_1D_3_PULSE_END = 140000;
    localparam int SYNFIRE_1D_3_INPUT_NEURON = 0;
    localparam fixed_t SYNFIRE_1D_3_PULSE_HEIGHT_Q8 = 32'sd20480;
    // Rows: receiving neuron. Column 2*n: source n excitatory channel;
    // column 2*n+1: source n inhibitory channel. Zero means no link.
    localparam fixed_t SYNFIRE_1D_3_SYNAPSE_COEFFICIENT_Q24 [0:2][0:5] = '{
        '{32'sd0, 32'sd0, 32'sd0, 32'sd0, 32'sd14728164, 32'sd0},
        '{32'sd14728164, 32'sd0, 32'sd0, 32'sd0, 32'sd0, 32'sd0},
        '{32'sd0, 32'sd0, 32'sd14728164, 32'sd0, 32'sd0, 32'sd0}
    };
    //                          Source neuron
    //                Neuron 0        Neuron 1        Neuron 2
    //                E      I        E      I        E      I
    // Target 0      [0,     0,       0,     0,       C,     0]
    // Target 1      [C,     0,       0,     0,       0,     0]
    // Target 2      [0,     0,       C,     0,       0,     0]

endpackage
