// This file is generated by scripts/generate_neuron_params.py.
// Edit the Python source values and rerun the script instead of editing this file.
// Values, formats, and conversion method reproduce the original research
// team's C_fixedpoint/Single_Neuron/neuron_fixed.c reference model.
// DOI: 10.1109/JETCAS.2023.3330069

package neuron_params_generated_pkg;

    localparam int VALUE_WIDTH = 32;
    localparam int STATE_FRAC_BITS = 24;
    localparam int CONSTANT_FRAC_BITS = 24;
    localparam int MATRIX_FRAC_BITS = 23;
    localparam int CURRENT_FRAC_BITS = 8;

    typedef logic signed [VALUE_WIDTH-1:0] fixed_t;

    // Initial state order: Vmem, VK, Vg, VNa.
    localparam fixed_t INITIAL_STATE [0:3] = '{
        -32'sd47494620, 32'sd35804256, -32'sd74339848, -32'sd74339848
    };

    // Constants use 24 fractional bits unless stated otherwise.
    localparam fixed_t DT = 32'sd16777;
    localparam fixed_t EXPMEL = 32'sd122987056;
    localparam fixed_t EXPVSAT = 32'sd110924240;
    localparam fixed_t EXPMVGK = 32'sd3823527;
    localparam fixed_t EXPVNA = 32'sd305345;
    localparam fixed_t EXPEK = 32'sd2288412;
    localparam fixed_t KP = -32'sd12582912;

    // Input current uses 8 fractional bits.
    localparam fixed_t INPUT_PULSE_HEIGHT = 32'sd25600;

    // Matrix coefficients use 23 fractional bits.
    localparam fixed_t NEURON_MATRIX [0:3][0:7] = '{
        '{32'sd593788, 32'sd169595, 32'sd11150, 32'sd20030094, -32'sd200433440, -32'sd75717656, 32'sd1133899, -32'sd1947070},
        '{32'sd593788, 32'sd169595, 32'sd11150, 32'sd20030094, -32'sd200433440, -32'sd75717656, 32'sd3444937, -32'sd1947070},
        '{32'sd584353, 32'sd166900, 32'sd10973, 32'sd36721840, -32'sd367461312, -32'sd74514560, 32'sd1115882, 32'sd3569629},
        '{32'sd547831, 32'sd156469, 32'sd10287, 32'sd172703920, -32'sd1728181632, -32'sd69857400, 32'sd1046139, 32'sd198276688}
    };

endpackage
