"""Generate fixed-point SystemVerilog constants for the FH neuron.

The values, fixed-point formats, and conversion method below are reproduced
from the original research team's C_fixedpoint/Single_Neuron/neuron_fixed.c.
The research code accompanies:

    S. Bhattacharyya, P. R. Ayyappan and J. O. Hasler,
    "Towards Scalable Digital Modeling of Networks of Biorealistic
    Silicon Neurons," IEEE JETCAS, 2023.
    DOI: 10.1109/JETCAS.2023.3330069

The conversion matches the research code's C macro:

    fi(value, fractional_bits) = (int)(value * 2^fractional_bits)

The source C arrays and variables use 32-bit IEEE-754 float values. This script
first reproduces that float precision. Python's int() then truncates toward
zero, just like the C cast to int. The generated constants are therefore a
reproduction of the published reference conversion, not a new quantisation
method.
"""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


VALUE_WIDTH = 32

# Fractional-bit counts used by the reference C model.
STATE_FRAC_BITS = 24
CONSTANT_FRAC_BITS = 24
MATRIX_FRAC_BITS = 23
CURRENT_FRAC_BITS = 8

# Initial state offsets from neuron_fixed.c.
OFFSET_A = 2.8309
OFFSET_B = -2.1341
OFFSET_C = 4.4310

INITIAL_STATE = [
    -OFFSET_A,  # Vmem
    -OFFSET_B,  # VK
    -OFFSET_C,  # Vg
    -OFFSET_C,  # VNa
]

# Model and simulation constants from neuron_fixed.c.
MODEL_CONSTANTS = {
    "DT": 0.001,
    "EXPMEL": 7.3306,
    "EXPVSAT": 6.6116,
    "EXPMVGK": 0.2279,
    "EXPVNA": 0.0182,
    "EXPEK": 0.1364,
    "KP": -0.75,
}

INPUT_PULSE_HEIGHT = 100.0

# Constant 4 by 8 neuron matrix from neuron_fixed.c.
NEURON_MATRIX = [
    [
        70.785082606739 / 1000,
        20.2173858708657 / 1000,
        1.32921811478727 / 1000,
        2387.77324751470 / 1000,
        -23893.5281204093 / 1000,
        -9026.24819333978 / 1000,
        135.171307831437 / 1000,
        -232.108910489866 / 1000,
    ],
    [
        70.7850826067390 / 1000,
        20.2173858708657 / 1000,
        1.32921811478727 / 1000,
        2387.77324751470 / 1000,
        -23893.5281204093 / 1000,
        -9026.24819333978 / 1000,
        410.668585361385 / 1000,
        -232.108910489866 / 1000,
    ],
    [
        69.6603580753146 / 1000,
        19.8961460133584 / 1000,
        1.30809778595160 / 1000,
        4377.58428711028 / 1000,
        -43804.8015540837 / 1000,
        -8882.82754034463 / 1000,
        133.023532053490 / 1000,
        425.533002564754 / 1000,
    ],
    [
        65.3065856956075 / 1000,
        18.6526368875235 / 1000,
        1.22634167432962 / 1000,
        20587.9115563489 / 1000,
        -206015.309127084 / 1000,
        -8327.65081907309 / 1000,
        124.709561300147 / 1000,
        23636.4240515513 / 1000,
    ],
]


def as_c_float(value: float) -> float:
    """Round a Python float to the same precision as a C float."""

    return struct.unpack("f", struct.pack("f", value))[0]


def to_fixed(value: float, fractional_bits: int) -> int:
    """Convert a C float value to a signed fixed-point integer."""

    c_value = as_c_float(value)
    return int(c_value * (1 << fractional_bits))


def sv_signed(value: int) -> str:
    """Format an integer as an explicit signed SystemVerilog literal."""

    if value < 0:
        return f"-{VALUE_WIDTH}'sd{abs(value)}"
    return f"{VALUE_WIDTH}'sd{value}"


def format_array(values: list[int], indent: str = "        ") -> str:
    """Format a one-dimensional SystemVerilog assignment pattern."""

    return indent + "'{" + ", ".join(sv_signed(value) for value in values) + "}"


def generate_package() -> str:
    """Build the complete SystemVerilog package as text."""

    initial_state = [to_fixed(value, STATE_FRAC_BITS) for value in INITIAL_STATE]
    fixed_constants = {
        name: to_fixed(value, CONSTANT_FRAC_BITS)
        for name, value in MODEL_CONSTANTS.items()
    }
    pulse_height = to_fixed(INPUT_PULSE_HEIGHT, CURRENT_FRAC_BITS)
    fixed_matrix = [
        [to_fixed(value, MATRIX_FRAC_BITS) for value in row]
        for row in NEURON_MATRIX
    ]

    lines = [
        "// This file is generated by scripts/generate_neuron_params.py.",
        "// Edit the Python source values and rerun the script instead of editing this file.",
        "// Values, formats, and conversion method reproduce the original research", 
        "// team's C_fixedpoint/Single_Neuron/neuron_fixed.c reference model.",
        "// DOI: 10.1109/JETCAS.2023.3330069",
        "",
        "package neuron_params_generated_pkg;",
        "",
        f"    localparam int VALUE_WIDTH = {VALUE_WIDTH};",
        f"    localparam int STATE_FRAC_BITS = {STATE_FRAC_BITS};",
        f"    localparam int CONSTANT_FRAC_BITS = {CONSTANT_FRAC_BITS};",
        f"    localparam int MATRIX_FRAC_BITS = {MATRIX_FRAC_BITS};",
        f"    localparam int CURRENT_FRAC_BITS = {CURRENT_FRAC_BITS};",
        "",
        "    typedef logic signed [VALUE_WIDTH-1:0] fixed_t;",
        "",
        "    // Initial state order: Vmem, VK, Vg, VNa.",
        "    localparam fixed_t INITIAL_STATE [0:3] = '{",
        "        " + ", ".join(sv_signed(value) for value in initial_state),
        "    };",
        "",
        "    // Constants use 24 fractional bits unless stated otherwise.",
    ]

    for name in ("DT", "EXPMEL", "EXPVSAT", "EXPMVGK", "EXPVNA", "EXPEK", "KP"):
        lines.append(
            f"    localparam fixed_t {name} = {sv_signed(fixed_constants[name])};"
        )

    lines.extend(
        [
            "",
            "    // Input current uses 8 fractional bits.",
            "    localparam fixed_t INPUT_PULSE_HEIGHT = " + sv_signed(pulse_height) + ";",
            "",
            "    // Matrix coefficients use 23 fractional bits.",
            "    localparam fixed_t NEURON_MATRIX [0:3][0:7] = '{",
        ]
    )

    for row_index, row in enumerate(fixed_matrix):
        comma = "," if row_index < len(fixed_matrix) - 1 else ""
        lines.append(format_array(row) + comma)

    lines.extend(
        [
            "    };",
            "",
            "endpackage",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    """Write the generated package, or check that it is current."""

    parser = argparse.ArgumentParser(
        description="Generate the fixed-point FH neuron SystemVerilog package."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated package is missing or out of date.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    output_path = repo_root / "hdl" / "neuron_params_generated_pkg.sv"
    generated_text = generate_package()

    if args.check:
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != generated_text:
            raise SystemExit(
                "hdl/neuron_params_generated_pkg.sv is out of date. "
                "Run: python scripts/generate_neuron_params.py"
            )
        print("hdl/neuron_params_generated_pkg.sv is up to date.")
        return

    output_path.write_text(generated_text, encoding="utf-8")
    print(f"Wrote {output_path.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
